# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='user')),
                ('image', models.ImageField(upload_to='albums', verbose_name='image')),
                ('image_url', models.URLField(unique=True, verbose_name='image URL')),
                ('twitter_creation_date', models.DateTimeField(verbose_name='twitter creation date')),
            ],
        ),
    ]
