# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='favorite count'),
        ),
    ]
