# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from twython import Twython


def add_token(apps, schema_editor):
    TwitterConnector = apps.get_model('collector', 'TwitterConnector')
    twitter_connector = TwitterConnector()
    twitter = Twython(
        settings.APP_KEY, settings.APP_SECRET, oauth_version=2)
    twitter_connector.token = twitter.obtain_access_token()
    twitter_connector.save()


def del_token(apps, schema_editor):
    TwitterConnector = apps.get_model('collector', 'TwitterConnector')
    TwitterConnector.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_token, del_token)
    ]
