# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:45
from __future__ import unicode_literals

from django.db import migrations


def add_token(apps, schema_editor):
    TwitterConnector = apps.get_model('collector', 'TwitterConnector')
    twitter = TwitterConnector()
    twitter.save()


def del_token(apps, schema_editor):
    TwitterConnector = apps.get_model('collector', 'TwitterConnector')
    TwitterConnector.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_token, del_token)
    ]
